//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserList
    {
        public int User_ID { get; set; }

        [Required]
        public string First_Name { get; set; }

        [Required]
        public string Last_Name { get; set; }

        [Required]
        public string Employee_ID { get; set; }
        public int Project_ID { get; set; }
        public int Task_ID { get; set; }

        public virtual ProjectList ProjectList { get; set; }
        public virtual TaskList TaskList { get; set; }
    }
}
